name: Deploy package

inputs:
  user:
    description: PyPI user
    required: false
    default: __token__

on: 
  push:
    tags:
    - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}