name: Deploy package

inputs:
  user:
    description: PyPI user
    required: false
    default: __token__

on: push
  tags:
  - v*

jobs:
  - name: Publish a Python distribution to PyPI
    uses: pypa/gh-action-pypi-publish@release/v1
    with:
      password: ${{ secrets.PYPI_API_TOKEN }}